### PR TITLE
Fix typos to make our tests green again

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by StephenFrey — APPROVED** [review]

**Review by StephenFrey — APPROVED** [review]

**Review by StephenFrey — APPROVED** [review]

**Comment by StephenFrey** [comment]
not sure why there is a conflict

**Review by StephenFrey — APPROVED** [review]

**Review by StephenFrey — APPROVED** [review]

**Comment by cclauss** [comment]
> not sure why there is a conflict

Are you able to click the `Resolve conflicts` button below?  (It is dimmed for me.)

**Comment by cclauss** [comment]
I resynced this to master.  That removed all corrections made to ./Pythonista/GameDevelopment/SpaceEscape.py but the typo fixes to the other files are here.

**Comment by cclauss** [comment]
Try to use underscores (_) rather than spaces ( ) in file paths.

**Comment by StephenFrey** [comment]
I was able to Commit this time can we run your tests again?

**Comment by cclauss** [comment]
Tests will run automatically on all pushes or pull requests.

**Comment by cclauss** [comment]
https://github.com/StephenFrey/CookBook/actions
```
./Pythonista/GameDevelopment/SPACE ESCAPE/space_escape_iphone:137: eachother  ==> each other
./Pythonista/GameDevelopment/SPACE ESCAPE/space_escape_iphone:137: Alo  ==> Also
./Pythonista/GameDevelopment/SPACE ESCAPE/space_escape_iphone:137: alows  ==> allows
./Pythonista/GameDevelopment/SPACE ESCAPE/space_escape_iphone:143: recieves  ==> receives
```

**Comment by StephenFrey** [comment]
just corrected

**Comment by StephenFrey** [comment]
thank you for what you do for python and the python community 😁

**Pull request merged**
